version: '3.8' 
networks: 
  cassandra: 
services: 
  cassandra1: 
    image: cassandra:4.0.13 
    container_name: cassandra1 
    hostname: cassandra1 
    networks: 
      - cassandra 
    ports: 
      - "9042:9042" 
      - "7199:7199"
    environment:  
        CASSANDRA_SEEDS: "cassandra1"   
        CASSANDRA_CLUSTER_NAME: cluster1 
        CASSANDRA_DC: dc1 
        CASSANDRA_RACK: rack1 
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch 
        CASSANDRA_NUM_TOKENS: 128      