version: '3.7'
networks: 
  cassandra: 
services:
  cassandra:
    image: cassandra:4.0.13
    container_name: cassandra
    hostname: cassandra
    networks: 
      - cassandra     
    ports:
      - "9042:9042"
      - "7199:7199"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    command: bash -c "export JVM_OPTS=\"$JVM_OPTS -javaagent:/jmx_exporter/jmx_prometheus_javaagent-1.0.1.jar=7072:/jmx_exporter/config.yml\" && cassandra -f -R"
    volumes:
      - ./jmx_exporter:/jmx_exporter

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks: 
      - cassandra       
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks: 
      - cassandra       
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  cassandra_data:
  grafana_data:
