version: '3.8' 
networks: 
  cassandra: 
services: 
  cassandra1: 
    image: cassandra:4.0.13 
    container_name: cassandra1 
    hostname: cassandra1 
    networks: 
      - cassandra 
    ports: 
      - "9042:9042" 
    environment:  
        CASSANDRA_SEEDS: "cassandra1"   
        CASSANDRA_CLUSTER_NAME: cluster1 
        CASSANDRA_DC: dc1 
        CASSANDRA_RACK: rack1 
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch 
        CASSANDRA_NUM_TOKENS: 128
  cassandra2: 
    image: cassandra:4.0.13 
    container_name: cassandra2 
    hostname: cassandra2 
    networks: 
      - cassandra 
    ports: 
      - "9043:9042" 
    environment:  
        CASSANDRA_SEEDS: "cassandra1"   
        CASSANDRA_CLUSTER_NAME: cluster1 
        CASSANDRA_DC: dc2 
        CASSANDRA_RACK: rack1 
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch 
        CASSANDRA_NUM_TOKENS: 128
  cassandra3: 
    image: cassandra:4.0.13 
    container_name: cassandra3 
    hostname: cassandra3 
    networks: 
      - cassandra 
    ports: 
      - "9044:9042" 
    environment:  
        CASSANDRA_SEEDS: "cassandra1"   
        CASSANDRA_CLUSTER_NAME: cluster1 
        CASSANDRA_DC: dc3 
        CASSANDRA_RACK: rack1 
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch 
        CASSANDRA_NUM_TOKENS: 128        